apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: go-app
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30033
  type: NodePort

