apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
  namespace: go-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - name: go-app
          image: siva9989/standalone-goapp:latest
          ports:
            - containerPort: 8081

