apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-sa
  namespace: webapp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-sa-binding
  namespace: webapp
subjects:
- kind: ServiceAccount
  name: test-sa
  namespace: webapp
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io