apiVersion: v1              # API version for Pods
kind: Pod                   # Resource type is a Pod
metadata:                   # Metadata for identifying the Pod
  name: my-pod              # Name of the Pod
  namespace: my-namespace   # Specifies the namespace this Pod belongs to
  labels:               # Labels assigned to Pods
    app: my-app
spec:                       # Specification of the Pod's desired state
  containers:               # List of containers to run in the Pod
    - name: goapp-container # Name of the container (for reference)
      #image: nginx           # Docker image to use (nginx web server)
      image: siva9989/standalone-goapp:latest
      ports:                 # Ports the container exposes
        - containerPort: 8081  # Port 80 (HTTP) inside the container
    - name: nginx-container # Name of the container (for reference)
      #image: nginx           # Docker image to use (nginx web server)
      image: siva9989/standalone-javaapp:latest
      ports:                 # Ports the container exposes
        - containerPort: 8080
