apiVersion: v1              # API version for Services
kind: Service               # Resource type is a Service
metadata:                   # Metadata for the Service
  name: my-service          # Name of the Service
  namespace: my-namespace   # Namespace scope
spec:                       # Specification of the Service
  selector:                 # Selects Pods to expose
    app: my-app             # Matches Pods with label "app: my-app"
  ports:                    # Ports the Service exposes
    - protocol: TCP         # Protocol (TCP or UDP)
      port: 80              # Port exposed by the Service
      targetPort: 80        # Port on the Pod to forward traffic to
  type: ClusterIP           # Service type (default, internal to cluster)
